### ISSUE TITLE
is there a way to compose a chord?

### ISSUE THREAD

**Issue by chevalierc** [vishnubob/python-midi#114]
Heres my Code

```
    pattern = midi.Pattern()
    pattern.make_ticks_rel()
    track = midi.Track()
    pattern.append(track)

    currentTick = 0

    for i in range(songLength):
        length = int( (440 / 16 ) * rhythms[i])
        for pitch in chords[i]:
            on = midi.NoteOnEvent(tick=currentTick, velocity=NOTE_VELOCITY, pitch=pitch)
            off = midi.NoteOffEvent(tick=currentTick + length, pitch=pitch)
            track.append(on)
            track.append(off)

        currentTick += length

    eot = midi.EndOfTrackEvent(tick=currentTick)
    track.append(eot)
    midi.write_midifile(outputFileName, pattern)
```

**Comment by semininja** [comment]
You would do well to read a little more about the basics of MIDI data. Your code seems to be pretty close, from a quick glance over it, but one thing to note (no pun intended) is that MIDI typically works by relative tick counts, rather than absolute position within the track. This means that all notes that are meant begin together should have NoteOnEvents before any NoteOffEvents occur for that chord. I don't know if there's a flag for marking time in absolute ticks, but if not, you'll want to make sure that you use relative tick counts during creation in order to avoid problems.

**Comment by chevalierc** [comment]
thanks for the suggestions. The issue was that fixed by pushing all the on events before the off events. I figured the order wouldn't matter as they had the time from start encoded. Much thanks!

```
pattern = midi.Pattern()
    pattern.make_ticks_abs()
    track = midi.Track()
    pattern.append(track)
    
    for i in range(songLength):
        length = int( (220 / 16 ) * rhythms[i])
        # for pitch in chords[i]:
        for pitch in chords[i]:
            on = midi.NoteOnEvent(tick=0, velocity=NOTE_VELOCITY, pitch=pitch)
            track.append(on)
        for pitch in chords[i]:
            off = midi.NoteOffEvent(tick=length, pitch=pitch)
            track.append(off)

    eot = midi.EndOfTrackEvent(tick=currentTick)
    track.append(eot)
    midi.write_midifile(outputFileName, pattern)
```
