### ISSUE TITLE
Questions on mididump.py

### ISSUE THREAD

**Issue by tleyden** [vishnubob/python-midi#57]
I downloaded this [America the Beautiful.midi](http://www.ajsmidi.com/patriotic/midi/america_the_beautiful.mid), and ran:

```
mididump.py america_the_beautiful_three_instruments.midi
```

which gave me [this output](https://gist.github.com/tleyden/80964d7a541dd7e96cd0)

and I had a few questions:

1. In [this line](https://gist.github.com/tleyden/80964d7a541dd7e96cd0#file-gistfile1-txt-L25): `midi.NoteOnEvent(tick=720, channel=0, data=[62, 126]),` what do the list elements in the `data` field represent?

1. Why are there duplicate events?  [this event](https://gist.github.com/tleyden/80964d7a541dd7e96cd0#file-gistfile1-txt-L29) seems identical to [this event](https://gist.github.com/tleyden/80964d7a541dd7e96cd0#file-gistfile1-txt-L31)

1. Why aren't the events sorted by tick?

1. In [Side Note: What is a MIDI Tick?](https://github.com/vishnubob/python-midi#side-note-what-is-a-midi-tick), you mention:

> First, a saved MIDI file encodes an initial Resolution and Tempo

In the [dumped file](https://gist.github.com/tleyden/80964d7a541dd7e96cd0#file-gistfile1-txt-L2), I'm only seeing a resolution:

```
midi.Pattern(format=1, resolution=240, tracks=\
```

Where should I look for the Tempo?

**Comment by tdhsmith** [comment]
> 1. In this line: midi.NoteOnEvent(tick=720, channel=0, data=[62, 126]), what do the list elements in the data field represent?

They are **pitch** and **velocity**. (cf. [`NoteEvent` source code](https://github.com/vishnubob/python-midi/blob/master/src/events.py#L113))

Pitch uses the standard MIDI note numbers:

![Image of piano keys, with the corresponding "MIDI number" of each key written alongside](http://newt.phys.unsw.edu.au/jw/graphics/notes.GIF)

Velocity is a measure from 0-127 of how hard the note was struck. If your MIDI track was generated from software or recorded from an instrument without velocity control, these values might all be the same.

>  2. Why are there duplicate events? this event seems identical to this event
> 3. Why aren't the events sorted by tick?

([There's some previous discussion here.](https://github.com/vishnubob/python-midi/issues/19)) By default tick values are relative, so they measure how many ticks have passed since the event before it. When you have things happening at the exact same time (like playing notes in a chord, or one note ending precisely as the next one begins) it will be listed as a series of events with `tick=0`.

Your events aren't duplicates, it's just two instances of a particular pitch occurring at the same time as something else.

As an alternative to the relative mode, you can convert a Pattern (or Track) to absolute tick values using `Pattern.make_ticks_abs()`. Since you're gonna be using a formula to compare outside data with MIDI ticks, that will probably be a lot easier. 

>  4. [...] Where should I look for the Tempo?

Tempo isn't set directly on the Pattern/Track, it's set through the `SetTempoEvent`. In your example they are all set in [their own track at the top](https://gist.github.com/tleyden/80964d7a541dd7e96cd0#file-gistfile1-txt-L5), which is fairly common IIRC.

`SetTempoEvent` data looks pretty goofy in the dumpout because it uses 3 bytes to store one value. So the first event has `data=[12, 11, 226]`, which sets the tempo to `(12 << 16) + (11 << 8) + 226 = 789474` **microseconds per quarter note**. Then the song stays at that speed for quite some time, until 49200 ticks later when it starts to slow down (presumably for the big finish). Every quarter note (240 ticks) from there on out it slows, until reaching a final speed of `(24 << 16) + (23 << 8) + 195 = 1578947` μspqn, which is about half the original speed.

You don't have to deal with the weird unit of measurement, by the way. The library includes [a converter to/from beats per minute](https://github.com/vishnubob/python-midi/blob/master/src/events.py#L303). Just use `TempoChangeEvent.bpm`.

**Comment by tdhsmith** [comment]
I should add that the meaning of the `data` field is always going to depend on what kind of event it is.

It's really just a simple way to handle how MIDI files are loaded and saved, while still allowing properties of events to be modified easily.

**Comment by tleyden** [comment]
> you can convert a Pattern (or Track) to absolute tick values using Pattern.make_ticks_abs(). Since you're gonna be using a formula to compare outside data with MIDI ticks, that will probably be a lot easier.

Great tip!  Yes I'll definitely need this.

Everything makes a lot more sense now.  Thanks for taking the time to write this up!
