### ISSUE TITLE
Question: converting from ticks to milliseconds

### ISSUE THREAD

**Issue by shimpe** [vishnubob/python-midi#61]
Hi,
I'm having some trouble using the framework to do what I want:
I read a midi file, I convert ticks to absolute but now I want to convert those ticks to milliseconds.

The documentation is confusing me: in several places it mentions the importance of a good time model and how conversions taking into account tempo and resolution are taken care of by the framework, but I don't see how to get the millisecond value for an event at all.  As for calculating it with the formula, it's not clear to me how to use the TempoMap or EventStreamIterator classes to track changing tempos. What are these streams they expect as a parameter? And what window length is required for the EventStreamIterator?

So the question is: how can I get a millisecond timevalue (relative to the start of the piece) of an 
event?

**Comment by vishnubob** [comment]
Tempo changes occur like any other event, which means they are assigned a tick, and any events subsequent of that tick are under the influence of the most recent tempo change.  The TempoMap is simply a convenience class that makes it easy to lookup a tempo for a given tick value (which is useful for playback).  In order to convert to wall clock time, you would have to scan through all of tempo changes, and calculate their wall clock equivalents, and sum up their wall-clock offsets (relative to each other).  Currently, there is no function in the library that solves the problem you are asking about, you will have to hammer out your own solution.

**Comment by shimpe** [comment]
Ok thanks, that confirms my suspicion then. It would be a nice addition to the library to resolve time. So maybe I should change this from question into feature request? :) 

Thanks for the explanation!

**Comment by vishnubob** [comment]
I'm open to pull requests, but this library is meant to serve as a thin API to make it easy to read and write MIDI files with Python.  Musical composition, interpretation and application is outside its scope, and that's where programmers such as yourself come in =)

Good luck!
