### ISSUE TITLE
Question: can different tracks have different tempos?

### ISSUE THREAD

**Issue by tleyden** [vishnubob/python-midi#64]
I am assuming different tracks in the same pattern all share a tempo, and it's a limitation with midi itself.  Can anyone confirm that?

**Comment by vishnubob** [comment]
MIDI dictates that tempo is global to a pattern.  In order to achieve different tempos within different tracks, you would need to set the tempo to the fastest BPM and use algebra to scale the on-time/off-time of events that track to a different beat.  The resolution will determine your quantization error, where a high value will mitigate rounding errors.  This is essentially what shuffle functions accomplish in modern composition software.

**Comment by tleyden** [comment]
Makes sense - thanks!
