### ISSUE TITLE
SetTempoEvent data interpretation?

### ISSUE THREAD

**Issue by semininja** [vishnubob/python-midi#74]
I am confused as to how one might make use of the SetTempoEvent data; I can't determine how the three values listed in each event are related to the tempo; for example, with a pattern resolution of 384, an event where the tempo should be set to 60 bpm, and therefore approximately 2604 ms/tick, has `data=[15, 66, 64]`. What correlation do those numbers have to the tempo?

**Comment by tdhsmith** [comment]
Resolution only expresses how many ticks there are per beat (it's called "resolution" because it determines how many samples the MIDI signal communicates for every beat). It does not have a bearing on the relation between time and meter.

Calculating from 60bpm:

```
60 bpm = 1 beat per second = 1000000 microseconds per beat
```

Tempo events are expressed in microseconds, so your event should have a value of 1 million. But the data array uses 8-bit words, so this number gets split up by powers of 256:

```
1000000 = (15 * 256^2) + (66 * 256) + (64) = [15, 66, 64]
```

But you don't actually have to worry about this form if you don't want. The `SetTempoEvent` class [has helpers for using BPM & microseconds-per-quarter-note](https://github.com/vishnubob/python-midi/blob/4b7a229f6b340e7424c1fccafa9ac543b9b3d605/src/events.py#L310): `get_bpm`, `set_bpm`, `get_mpqn`, & `set_mqpn`.

**Comment by semininja** [comment]
`get_mpqn` is handy. Why not make the data values hex, though, so that you can just concatenate and convert?

**Comment by tdhsmith** [comment]
I can't speak for @vishnubob, but I think the point is that the data array should always try to parallel the MIDI's binary data (and Python handles hexadecimal as strings, so that would be a lot of conversion work), and getters/setters should be the primary method of interacting with the values. 

Also, among the non-`varlen` events, nearly all of them have word-width data fields that are naturally interpreted as integers. The tempo event might be the only exception.
